### ISSUE TITLE
Cannot compile bindings.cpp after generating bindings

### ISSUE THREAD

**Issue by epitaque** [jacksondunstan/UnityNativeScripting#8]
Using Windows 10 and Visual Studio 15 2017. If I follow your instructions under Windows, everything works, and the example ball moves back and forth. But if I click NativeScript -> Generate Bindings, and then go back to Visual Studio to compile, I get several errors from Bindings.cpp:
- C2027	use of undefined type 'System::IEquatable_1<UnityEngine::Vector3>'	NativeScript (Bindings.cpp Line 3872)
- C2079	'UnityEngine::Vector3::operator System::IEquatable_1<UnityEngine::Vector3>' uses undefined struct 'System::IEquatable_1<UnityEngine::Vector3>'	NativeScript (Bindings.cpp Line 3872)
- C2027	use of undefined type 'System::IEquatable_1<UnityEngine::Vector3>'	NativeScript (Bindings.cpp Line 3884)

The reason I wanted to generate the bindings again was to add support for arrays (as you described how to do in [another issue](https://github.com/jacksondunstan/UnityNativeScripting/issues/5)). Attached are the generated Bindings.h and Bindings.cpp that give compile errors. Do you know how to make it so that the code generator makes compilable files?

[Bindings.zip](https://github.com/jacksondunstan/UnityNativeScripting/files/1958179/Bindings.zip)

**Comment by jacksondunstan** [comment]
Hi @brianhoy, it looks from those errors like you need to add `IEquatable<Vector3>` to `NativeScriptTypes.json` to support boxing `Vector3` to `IEquatable<Vector3>`. To do this, add on to the `GenericParams` section with `Types` having `UnityEngine.Vector3` following the pattern there.

As to why this is necessary, I suspect you're using the Unity 2018.2 beta. In Unity 2017.3, 2017.4, and the 2018.1 beta, there's no need for this because `Vector3` doesn't implement `IEquatable<Vector3>`.  However, that was added in the 2018.2 beta, so you'll need to add support for it in the JSON config.

Please let me know if this solution doesn't work for you and I'll reopen the issue. Thanks for using UnityNativeScripting and reporting the issue so thoroughly! 👍
